baseURL = "/"
relativeurls = true

languageCode = "en-us"
title = "Tan Ho"
theme = "avicenna"
googleAnalytics = "UA-1234-6"
timeout=3000

[params]
  subtitle= "Senior Java Software Engineer"
  interests="Building websites, mobile apps "
  cv_name= "cv.pdf"

[[params.affilation]]
  name = "Localize Direct Vietnam"
  position = "Senior Java Developer"
  contact = "th@localizedirect.com"

[[params.social]]
  name = "Twitter"
  icon = "twitter"
  url = "https://twitter.com/nottanho"

[[params.social]]
  name = "LinkedIn"
  icon = "linkedin"
  url = "https://linkedin.com/in/honhattan/"

[[params.apps]]
	[[params.apps.app]]
		name = "Easy Keep"
		description  = "Keep your everything."
		play_store_link = "https://play.google.com/store/apps/details?id=net.honhattan.easykeep"
		app_store_link = ""
